### ISSUE TITLE
Update Time

### ISSUE THREAD

**Issue by victors1681** [COVID19Tracking/covid-tracking-api#12]
Hi, why the API is taking so long to update the data? I think is updating the data once per day.

**Comment by webmasterkai** [comment]
The API is pulling live results from the Google Sheets once very 5 minutes. Note that `/api/us/daily` and `/api/states/daily` is updated only once per day.

If you want the most recent values you'll need to request `/api/us` or `/api/states`.

Please re-open this issue if I misunderstood the issue. Thanks!
