### ISSUE TITLE
add FIPS codes to states and counties

### ISSUE THREAD

**Issue by burritojustice** [COVID19Tracking/covid-tracking-api#13]
Could we add FIPS codes as a column/property in the CSV/JSON output for states and counties? It would make it much easier to join it to other datasets.

https://www.census.gov/geographies/reference-files/2017/demo/popest/2017-fips.html

**Comment by webmasterkai** [comment]
I've added `fips` to the `/states/info` endpoint. Is that sufficient?

Haven't added counties yet.

Not sure about the following:
- 'Federated States Of Micronesia'
- 'Marshall Islands'
- 'Northern Mariana Islands'

**Comment by burritojustice** [comment]
Thanks! Sorry, didn't realize the territories aren't in there -- wikipedia has an inclusive list:

https://en.wikipedia.org/wiki/Federal_Information_Processing_Standard_state_code

```
American Samoa	AS	60
Federated States of Micronesia 	FM 	64
Guam	GU	66
Marshall Islands	MH	68
Northern Mariana Islands	MP	69
Puerto Rico	PR	72
Virgin Islands	VI	78
```

**Comment by burritojustice** [comment]
did a PR https://github.com/COVID19Tracking/covid-tracking-api/pull/18
