### ISSUE TITLE
Calculate daily numbers for fields

### ISSUE THREAD

**Issue by goleary** [COVID19Tracking/covid-tracking-api#15]
data-viz folks would love it if some additional fields were added to the API for the following endpoints (in order of priority for the endpoints):

- `/api/us/daily` 
- `/api/us`
- `/api/states`
- `/api/states/daily` 

Here are the fields
- `newPositive` - delta of positive from day[n] & day[n-1]
- `newNegative` - delta of negative from day[n] & day[n-1]
- `newDeath` - delta of death from day[n] & day[n-1]
- `newHospitalized` - delta of hospitalized from day[n] & day[n-1]
- `newTotal` (not using this one, so less important but probably good for )

**Comment by webmasterkai** [comment]
I've added the following fields:

- `deathIncrease`
- `hospitalizedIncrease`
- `negativeIncrease`
- `positiveIncrease`
- `totalTestResultsIncrease`

I've just given it a spot check and didn't notice anything strange yet...

I can figure out a solution for /us and /states next.
