### ISSUE TITLE
create API endpoint for CDC Test #s

### ISSUE THREAD

**Issue by goleary** [COVID19Tracking/covid-tracking-api#16]
https://docs.google.com/spreadsheets/d/16gBHQ7dCJK1psqEMasmLKiFlzoNKcfNujVpmHLHldSY/edit#gid=0
probably best to keep this one out of the docs.

endpoint suggestion:
`/api/cdc/daily`

let me know if there is any problem with this data appearing to the side:
![image](https://user-images.githubusercontent.com/16123225/77574881-e9cb1280-6e8f-11ea-9163-d22ab524f007.png)

Pro

**Comment by webmasterkai** [comment]
https://covidtracking.com/api/cdc/daily or you might have to try:
https://covid.cape.io/cdc/daily

**Comment by goleary** [comment]
unreal, thanks for this
