### ISSUE TITLE
Add time stamp to https://covidtracking.com/api/us endpoint

### ISSUE THREAD

**Issue by curatemymind** [COVID19Tracking/covid-tracking-api#24]
Hey, I wanted to know if you guys could add a last updated timestamp to this endpoint!

https://covidtracking.com/api/us

**Comment by webmasterkai** [comment]
Do you want a timestamp of the last change? It isn't necessarily a full update, just anytime any of the values change?

**Comment by curatemymind** [comment]
Yes, anytime the values fluctuate, thank you!

**Comment by webmasterkai** [comment]
I added a `hash` and `lastModified` properties. I haven't thoroughly tested or documented it yet.
* `hash` is changed every time the data changes. Survives cache a reset.
* `lastModified` is the date the API cache was last updated. So even if the values didn't change but the cache was manually cleared or reset the date will reflect that time of **reset** and doesn't necessarily indicate an update was made. Manual cache clearing is rare however.
