### ISSUE TITLE
add FIPS code to /states and /states/daily

### ISSUE THREAD

**Issue by burritojustice** [COVID19Tracking/covid-tracking-api#25]
Thanks for adding the FIPS codes -- I see it in the states info, but I was hoping we could also add it to `/api/states` and  `/api/states/daily` (and the CSVs). 

This would greatly simplify joining it to geospatial (and other) data, and having a widely used unique ID in the primary endpoints would be a good precedent to set, especially if we get more county data.

**Comment by webmasterkai** [comment]
This has been added now. It should take less than 10 minutes to start showing up. Please reopen the issue if you run into trouble. Thanks!

**Comment by burritojustice** [comment]
sweet, thank you!
