### ISSUE TITLE
CORS disabled on states end point

### ISSUE THREAD

**Issue by richcorbs** [COVID19Tracking/covid-tracking-api#26]
The `Access-Control-Allow-Origin` header isn't being sent from the `/api/states` end point.

The `/api/us` endpoint still works fine.

**Comment by webmasterkai** [comment]
I'm seeing it still. Can you give any further details that would help reproduce the issue?

**Comment by richcorbs** [comment]
From a page running on localhost I get the CORS error. It worked all day until just now.

The attached screenshots show the `us` endpoint responding with the right `access-control-allow-origin: *` header and the `states` endpoint responding without it. 

![Screen Shot 2020-03-27 at 5 36 23 PM](https://user-images.githubusercontent.com/437167/77808579-8f79af80-7051-11ea-89c7-8ad2b77f96e3.png)

![Screen Shot 2020-03-27 at 5 36 07 PM](https://user-images.githubusercontent.com/437167/77808581-90aadc80-7051-11ea-9da5-df7766bc0916.png)

**Comment by webmasterkai** [comment]
Looks like you're getting a 500 error from `/api/states.json`. The quick fix is to remove the `.json` at the end of the url. Try `/api/states` instead. I'll figure out why there's a 500 error is happening.

**Comment by richcorbs** [comment]
I changed to `/api/states` and everything works again. Thanks!

Nevertheless, `/api/states.json` was working literally all day until just now and `/api/us.json` is still working. I'll close the ticket but there is some inconsistent behavior in the endpoints.
