### ISSUE TITLE
Broken links in NJ

### ISSUE THREAD

**Issue by bogosj** [COVID19Tracking/covid-tracking-api#27]
The two links in the sentence "There's a dashboard available but the testing data there is not as comprehensive as this table." are broken because the URL doesn't have a protocol https://.

Not sure where else to report this.

**Comment by jasonlcrane** [comment]
Hi @bogosj, I created a new issue on the covid-tracking-data repo for this, since I don't think it's an API issue necessarily.

**Comment by bogosj** [comment]
Thank you, I didn't see that project. That sounds like the right place for it.
