### ISSUE TITLE
Create Github action to auto deploy the API based on master

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/covid-tracking-api#29]
https://github.com/cloudflare/wrangler-action

**Comment by pspeter3** [comment]
https://github.com/features/actions

**Comment by pspeter3** [comment]
Based on conversations in Slack, we're thinking about moving this to Netlify functions. Is this task still relevant?

**Comment by webmasterkai** [comment]
Closing since we've moved to using static files and netlify functions.
