### ISSUE TITLE
api/state/daily Is out of date with spreadsheet

### ISSUE THREAD

**Issue by shawnwildermuth** [COVID19Tracking/covid-tracking-api#30]
Looks like the data in the api is not being updated correctly. The website shows newer data than the APIs. See the Georgia data for an example.

**Comment by webmasterkai** [comment]
The website uses the API for its data. I'm thinking this was a cache issue on an edge server. Please reopen if you notice it again. Thanks!

**Comment by shawnwildermuth** [comment]
Thanks
