### ISSUE TITLE
better repo description

### ISSUE THREAD

**Issue by tomByrer** [COVID19Tracking/covid-tracking-api#5]
Could you change description to something like:
`COVID Rest & GraphQL API for US data, using Cloudflare Workers`
?
Honestly IDK, but seems some scrapers like [this Awesome List](https://github.com/soroushchehresa/awesome-coronavirus#api) use it, so a better description could help others.

Thanks for all your hard work!

**Comment by webmasterkai** [comment]
Yes, thank you!
