### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by ajinkya-k** [COVID19Tracking/covid-tracking-api#7]
The CSV API seem to keep changing. I keep getting 403. Some API (e.g. States daily) seem to be using http while some others (e.g. US daily) seem to be using https. Could someone clarify this?

**Comment by aflores** [comment]
Hello,
I am having a similar problem retrieving the data as JSON using pandas.
Requests fail most of the time.

Here is my code:
 
data_url = "https://covidtracking.com/api/states/daily"
daily = pd.read_json(data_url)

Results in:
HTTPError: HTTP Error 403: Forbidden


Thank you for making this data available

**Comment by webmasterkai** [comment]
Do you get the same error if you use https://covid.cape.io/states/daily ?

**Comment by webmasterkai** [comment]
I'm thinking this is related to some firewall rules I had set that were too strict. I'm seeing some `Python-urllib/3.6` user agents (and a few others) that were being blocked. I made some adjustments that should prevent this in the future.

**Comment by aflores** [comment]
It is working for me now. 

Thank you!

**Comment by ajinkya-k** [comment]
Thanks!
