### ISSUE TITLE
/api/states giving dates with wrong year (1970)

### ISSUE THREAD

**Issue by papakpmartin** [COVID19Tracking/covid-tracking-api#8]
Looking at https://covidtracking.com/api/states as of now (2020-03-21T23:30:00Z) has entries like this: `"dateModified":"1970-03-21T18:47:00Z"`

**Comment by webmasterkai** [comment]
Thanks for reporting this. Do you mind confirming it is working now as expected?

**Comment by papakpmartin** [comment]
Looking good to me! I'll not be so presumptuous as to close this, though... leave it to the pros.
